### ISSUE TITLE
Can it be integrated with the default file search?

### ISSUE THREAD

**Issue by jt-wang** [ichitaro/alfred-grep#1]
Hi ichitaro,

I searched for a while for the regex search workflow and found your repo here. It is quite marvelous.

I would like to know if it is possible to integrate "alfred-grep" into the default search of Alfred? 
For example, normally I type "screenshot" in the search box and Alfred will list the files whose names contain "screenshot", what I imagine is that  I type **"re /screenshot.*\.png$/"** in the search box and Alfred will list all the files according to the regex, and I can do anything like **open it with corresponding apps** ( Preview.app in this case) without editing it in the text editor, or **preview it in Alfred.**

Many thanks.

**Comment by ichitaro** [comment]
Hi,

Unfortunately, I don't know how to integrate with Alfred's default file navigation.
However, the following hotkeys may be useful.

**Open file in default application**

`⌘O`

**Quick Look**

Tap the `shift` key (or `⌘Y`)

**Show list of available Actions for selected item**

`→`  (or `tab`)

You can modify the keys used to show file actions, as well as which actions you want to see in the Features > File Search > Actions preferences.

**Comment by jt-wang** [comment]
@ichitaro Many thanks! I will explore it!
