### ISSUE TITLE
Where is settings.json?

### ISSUE THREAD

**Issue by jeremycherfas** [ichitaro/alfred-grep#2]
Hello

Thanks for a useful workflow. However, I do not use Sublime Text, but I cannot find the file `settings.json` that you say I can edit to use another editor.

Many thanks.

Jeremy

**Comment by ichitaro** [comment]
You can find that file in the following way.

**Alfred Preferences > Workflows > Right-click the grep workflow in the left sidebar > Open in Finder**

![2018-10-06 13 20 57](https://user-images.githubusercontent.com/2506174/46567532-399ddd00-c96f-11e8-81cf-fea6e44e97f6.png)

**Comment by jeremycherfas** [comment]
Thank you.
