### ISSUE TITLE
Breaks in Alfred 4

### ISSUE THREAD

**Issue by Xiao6** [ichitaro/alfred-grep#4]
It breaks in Alfred4 with error
```
STDERR: grep[Run Script] 277:278: syntax error: Expected “given”, “with”, “without”, other parameter name, etc. but found “(”. (-2741)
```

**Comment by ichitaro** [comment]
Please set `alfred_app_name` in `settings.json` as follows.
```
{
	// Make sure the version matches
	"alfred_app_name": "Alfred 4",
	...
}
```

You can find `settings.json` in:
**Alfred Preferences > Workflows > Right-click the grep workflow in the left sidebar > Open in Finder**

Or check the latest version.

**Comment by Xiao6** [comment]
Thanks for quick reply. It works!
